# fly.toml file generated for cytube-sort-bot on 2023-04-14T01:58:38-07:00

app = "cytube-sort-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[deploy]

[env]
  enableLogging = "true"
  room = "fourwallsandaroof"
  serverBaseUrl = "https://cytu.be"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
